export const roundClashConfig = Object.freeze({
  introDuration: 2,
  overlayFadeDuration: 0.3,
  healthDuration: 7,
  damageDurationWithHealing: 6,
  healingDuration: 1,
  effectCountMin: 10,
  effectCountMax: 15,
  effectStartOffset: 0.25,
  effectEndPadding: 0.9,
  effectXMin: 8,
  effectXMax: 92,
  effectYMin: 8,
  effectYMax: 92,
  lightningDuration: 0.5,
  explosionDuration: 0.62,
  flashDuration: 0.34,
  lightningShakeDuration: 0.24,
  explosionShakeDuration: 0.38,
  flashShakeDuration: 0.16,
})
