export interface ColorLightningConfig {
  strandCount: number
  coreColor: string
  middleColor: string
  edgeColor: string
  coreRadius: number
  edgeRadius: number
  coreOpacity: number
  edgeOpacity: number
  sharedAnchorRadiusMin: number
  sharedAnchorRadiusMax: number
  strandAnchorRadiusMin: number
  strandAnchorRadiusMax: number
  strandAnchorAngleRandomness: number
  subdivisions: number
  expansionBase: number
  expansionAmount: number
  expansionAngleRandomness: number
  jitter: number
  minTubularSegments: number
  tubularSegmentsPerPoint: number
  radialSegments: number
  pathDelay: number
  maxCascadeDuration: number
  travelDuration: number
  flickerOpacityFactor: number
  flickerDuration: number
  flickerCount: number
  fadeDuration: number
  depthTest: boolean
  depthWrite: boolean
  additiveBlending: boolean
  doubleSided: boolean
  toneMapped: boolean
  renderOrderBase: number
}

export function createColorLightningConfig(): ColorLightningConfig {
  return {
    strandCount: 2,
    coreColor: '#ffcccc',
    middleColor: '#39c8ff',
    edgeColor: '#2c60a5',
    coreRadius: 0.0025,
    edgeRadius: 0.004,
    coreOpacity: 1,
    edgeOpacity: 0.7,
    sharedAnchorRadiusMin: 0.005,
    sharedAnchorRadiusMax: 0.004,
    strandAnchorRadiusMin: 0.038,
    strandAnchorRadiusMax: 0.024,
    strandAnchorAngleRandomness: 3.78,
    subdivisions: 6,
    expansionBase: 0.082,
    expansionAmount: 0.005,
    expansionAngleRandomness: 6.283185307179586,
    jitter: 0,
    minTubularSegments: 1,
    tubularSegmentsPerPoint: 1,
    radialSegments: 3,
    pathDelay: 0.155,
    maxCascadeDuration: 0.11,
    travelDuration: 0.79,
    flickerOpacityFactor: 0.08,
    flickerDuration: 0.035,
    flickerCount: 3,
    fadeDuration: 0.13,
    depthTest: false,
    depthWrite: false,
    additiveBlending: true,
    doubleSided: true,
    toneMapped: true,
    renderOrderBase: 13,
  }
}
